services:
  taskmanager:
    build: .
    environment:
      - DB_URL=jdbc:mysql://db:3306/taskmanager
      - DB_USER=root
      - DB_PASS=root
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_DATABASE=taskmanager
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10